{{- if and (eq .Values.mode "multi") .Values.auth.oidc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ok8s.fullname" . }}-auth-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    tailscale.com/hostname: {{ .Values.auth.oidc.hostname }}-{{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: {{ include "ok8s.fullname" . }}-oauth2-proxy
      port:
        number: 4180
{{- end }}
