{{- if and (eq .Values.mode "multi") .Values.auth.oidc.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ok8s.fullname" . }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
data:
  oauth2-proxy.cfg: |
    http_address = "0.0.0.0:4180"
    reverse_proxy = true
    provider = "oidc"
    client_id = {{ .Values.auth.oidc.clientId | quote }}
    client_secret = {{ .Values.auth.oidc.clientSecret | quote }}
    oidc_issuer_url = {{ .Values.auth.oidc.provider | quote }}
    cookie_secret = {{ .Values.auth.oidc.cookieSecret | quote }}
    email_domains = [{{ .Values.auth.oidc.emailDomain | quote }}]
    redirect_url = "https://{{ .Values.auth.oidc.hostname }}-{{ .Release.Namespace }}.{{ .Values.auth.oidc.cookieDomain | trimPrefix "." }}/oauth2/callback"
    {{- if .Values.auth.oidc.cookieDomain }}
    cookie_domains = [{{ .Values.auth.oidc.cookieDomain | quote }}]
    {{- end }}
    pass_user_headers = true
    pass_access_token = true
    set_xauthrequest = true
    pass_host_header = true
{{- end }}
