{{- if and (eq .Values.mode "multi") .Values.auth.oidc.enabled }}
apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: {{ include "ok8s.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: oauth2-proxy
spec:
  tailscale:
    hostname: {{ .Values.auth.oidc.hostname }}-{{ .Release.Namespace }}
{{- end }}
