{{- if and (eq .Values.mode "multi") .Values.auth.oidc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ok8s.fullname" . }}-oauth2-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oauth2-proxy
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: 4180
    targetPort: 4180
    protocol: TCP
{{- end }}
