repos:
  - repo: local
    hooks:
      - id: operator-test
        name: operator-test
        entry: cd operator && make test
        language: system
        pass_filenames: false
        types: [go]
        files: "^operator/"
      - id: helm-lint
        name: helm-lint
        entry: helm lint chart/
        language: system
        pass_filenames: false
        types: [yaml]
        files: "^chart/"
