{{- if eq .Values.mode "single" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencode-k8s-helm.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opencode-k8s-helm.labels" . | nindent 4 }}
data:
  opencode.jsonc: |
    {{- include "opencode-k8s-helm.opencodeConfig" . | nindent 4 }}
  oh-my-opencode.jsonc: |
    {{- include "opencode-k8s-helm.omoConfig" . | nindent 4 }}
{{- end }}
