{{- if eq .Values.mode "single" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ok8s.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
data:
  opencode.jsonc: |
    {{- include "ok8s.opencodeConfig" . | nindent 4 }}
  oh-my-opencode.jsonc: |
    {{- include "ok8s.omoConfig" . | nindent 4 }}
{{- end }}
