{{- if and .Values.identity.enabled .Values.identity.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ok8s.fullname" . }}-identity
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.identity.files }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
