{{- if and (eq .Values.mode "single") .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ok8s.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
  annotations:
    tailscale.com/hostname: {{ .Values.ingress.hostname | quote }}
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: {{ include "ok8s.fullname" . }}
      port:
        number: 4096
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
{{- end }}
