{{- /*
Single-user mode: shared kubedock Service.
*/ -}}
{{- if and .Values.kubedock.enabled (eq .Values.mode "single") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ok8s.fullname" . }}-kubedock-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ok8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: kubedock
spec:
  type: ClusterIP
  selector:
    {{- include "ok8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: kubedock
  ports:
  - protocol: TCP
    port: {{ .Values.kubedock.port }}
    targetPort: {{ .Values.kubedock.port }}
    name: api
{{- end }}
