---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - opencode.opencode.io
  resources:
  - opencodeworkspaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - opencode.opencode.io
  resources:
  - opencodeworkspaces/finalizers
  verbs:
  - update
- apiGroups:
  - opencode.opencode.io
  resources:
  - opencodeworkspaces/status
  verbs:
  - get
  - patch
  - update
