apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: ok8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: ok8s-operator-controller-manager
  namespace: system
