{{- if .Values.authentik.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ok8s.fullname" . }}-authentik-redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
      - name: redis
        image: "{{ .Values.authentik.redis.image.repository }}:{{ .Values.authentik.redis.image.tag }}"
        command: ["redis-server", "--requirepass", "$(REDIS_PASSWORD)"]
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "ok8s.fullname" . }}-authentik-redis
              key: password
        ports:
        - containerPort: 6379
        resources: {{ toYaml .Values.authentik.redis.resources | nindent 10 }}
{{- end }}