apiVersion: opencode.opencode.io/v1alpha1
kind: OpenCodeWorkspace
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: opencodeworkspace-sample
spec:
  # TODO(user): Add fields here
